### PR TITLE
&& Herr Hehr

### PR DESCRIPTION
**Pull request by jed**

### CODE REVIEW

**Comment by ZeeJab** [comment]
<3!

**Comment by jed** [comment]
wait, did i screw this up? there are two @copasetickid shouts now, blarg.

**Comment by copasetickid** [comment]
Looks like you cloned my twitter details. That's an easy fix for anyone at a laptop. I'm currently on my cellular phone.

**Comment by philduffy** [comment]
I think 2 Rushaines is a feature not a bug tbh

**Comment by jed** [comment]
MORE LIKE COPYSETICKID AMIRITE?

**Comment by philduffy** [comment]
6/10

**Comment by ZeeJab** [comment]
Solid

**Pull request merged**
